image: python:3.10
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
    - .cache/pip
    - venv/
before_script:
  - cat /etc/os-release
  - python -V || python3 -V
  - export DEBIAN_FRONTEND=noninteractive
  - export TZ=Europe/Stockholm
  - apt-get update -y && apt-get install -y gdal-bin postgresql postgresql-contrib libpq5 postgis
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt  # On Ubuntu 22.04 pip uses python3, so we don't need to use "||" like for python3
test:
  script:
    - ./manage.py test
