services:
  nginx:
    ports:
      - "80:80"
  db:
    volumes:
      - /var/lib/smartakartan_db:/var/lib/postgresql/data:z
  api:
    environment:
      - HOST=localhost
      - SCHEME=http
    volumes:
      - ./django-backend:/code:z
      - ./media:/media:z
  web:
    volumes:
      - ./react-frontend/src:/react-frontend/src:z
      - ./react-frontend/public:/react-frontend/public:z
