version: "3.8"

services:
  db:
    image: postgis/postgis:14-3.3  # This version was recommended "for new users" 2022-11-03
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      TZ: Europe/Stockholm
      POSTGRES_PASSWORD: nwKnN7kgftitCpc  # TODO: Security, see "Docker secrets" https://hub.docker.com/_/postgres
      POSTGRES_DB: smarta_kartan_db  # If not given, the db will be named after the admin user (probably "postgres")
  api:
    build: .
    environment:
      - PUBLIC_URL=smartakartan.entrop.mywire.org
    ports:
      - "8097:8000"
    depends_on:
      - db
  web:
    build: ./react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./react-frontend:/react-frontend
    depends_on:
      - api

volumes:
  pg_data:

# POSTGRES_HOST_AUTH_METHOD: trust

# docker-compose up -d
# docker-compose up -d --build
