# Generated by Django 4.1.1 on 2023-01-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativedescriptiontext',
            name='text',
            field=models.TextField(max_length=32767),
        ),
    ]
