# Generated by Django 4.1.1 on 2022-12-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_location_initiative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='description',
            field=models.CharField(max_length=32768),
        ),
    ]
