# Generated by Django 4.1.5 on 2023-01-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_initiativedescriptiontext_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='title',
            field=models.CharField(default='default region string', max_length=127, unique=True),
            preserve_default=False,
        ),
    ]
