# Generated by Django 4.1.4 on 2022-12-14 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_initiative_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.RenameField(
            model_name='initiative',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='address',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='online_only',
        ),
        migrations.AlterField(
            model_name='initiative',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='initiative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='website.initiative'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
