# Generated by Django 4.1.4 on 2023-02-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_region_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativedescriptiontext',
            name='sk3_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='initiativetitletext',
            name='sk3_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
