# Generated by Django 4.1.1 on 2023-02-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_initiativedescriptiontext_sk3_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sk3_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('slug', models.SlugField(max_length=127, unique=True)),
                ('title', models.CharField(max_length=127)),
            ],
        ),
        migrations.AddField(
            model_name='initiative',
            name='tags',
            field=models.ManyToManyField(to='website.tag'),
        ),
    ]
