# Generated by Django 4.1.1 on 2023-02-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_initiativedescriptiontext_sk3_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='main_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
