# Generated by Django 4.1.4 on 2022-12-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_initiative_sk3_id_location_sk3_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='sk3_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
