# Generated by Django 4.1.1 on 2023-01-11 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0006_alter_location_sk3_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stub', models.CharField(max_length=127, unique=True)),
                ('welcome_message_html', models.CharField(max_length=32767)),
            ],
        ),
        migrations.AddField(
            model_name='initiative',
            name='region',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='regions',
                to='website.region'),
            preserve_default=False,
        ),
    ]
