# Generated by Django 4.1.1 on 2023-01-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_region_initiative_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='stub',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='region',
            name='sk3_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
