# Generated by Django 4.1.1 on 2023-01-23 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_stub_region_slug_region_sk3_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TextItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='description',
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='title',
        ),
        migrations.CreateModel(
            name='LanguageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32767)),
                ('text_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_items', to='website.textitem')),
            ],
        ),
    ]
