# Generated by Django 4.1.4 on 2023-01-23 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_language_textitem_remove_initiative_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativeTitleText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=2)),
                ('text', models.CharField(max_length=32767)),
            ],
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AddField(
            model_name='initiative',
            name='description',
            field=models.CharField(default='empty by default', max_length=32767),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(max_length=127, unique=True),
        ),
        migrations.DeleteModel(
            name='LanguageText',
        ),
        migrations.DeleteModel(
            name='TextItem',
        ),
        migrations.AddField(
            model_name='initiativetitletext',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='website.initiative'),
        ),
    ]
