# Generated by Django 4.1.1 on 2023-01-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_initiativetitletext_delete_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativetitletext',
            name='sk3_initiative_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='initiative',
            name='description',
            field=models.CharField(default='TODO: Change to dynamic language', max_length=32767),
        ),
    ]
