# Generated by Django 4.1.6 on 2023-02-21 10:03

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.linestring
import django.contrib.gis.geos.polygon
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='area',
            field=django.contrib.gis.db.models.fields.PolygonField(default=django.contrib.gis.geos.polygon.Polygon(django.contrib.gis.geos.linestring.LinearRing(((12, 58), (12.1, 58.1), (12.1, 58.2), (12, 58)))), srid=4326),
        ),
    ]
