# Generated by Django 4.2 on 2023-04-20 13:43

from django.db import migrations, models
import django.db.models.deletion
from slugify import slugify


def add_slug(apps, schema_editor):
    initiatives = apps.get_model("website", "initiative")
    itts = apps.get_model("website", "InitiativeTitleText")
    for initiative in initiatives.objects.all():
        try:
            itt = initiative.initiative_title_texts.get(language_code='en')
        except itts.DoesNotExist:
            itt = initiative.initiative_title_texts.get(language_code='sv')

        possible_slug = slugify(itt.text)
        n = 0
        while 1:
            try:
                initiatives.objects.get(slug=possible_slug)
                n += 1
                possible_slug = slugify(itt.text) + str(n)
            except initiatives.DoesNotExist:
                initiative.slug = possible_slug
                initiative.save()
                break

def delete_loc_without_initiative(apps, schema_editor):
    locations = apps.get_model("website", "location")
    loc_without_init = locations.objects.filter(initiative=None)
    print(f"Deleting {len(loc_without_init)} locations.")
    loc_without_init.delete()

def migrate_title_and_descriptions(apps, schema_editor):
    titles = apps.get_model("website", "InitiativeTitleText")
    description = apps.get_model("website", "InitiativeDescriptionText")
    translations = apps.get_model("website", "InitiativeTranslation")
    for title in titles.objects.all():
        translation = translations.objects.create(language_code=title.language_code, initiative=title.initiative, title=title.text)
        desc = description.objects.get(initiative=title.initiative, language_code=title.language_code)
        translation.description = desc.text
        translation.sk3_id = title.sk3_id
        translation.save()

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_region_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sk3_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('language_code', models.CharField(max_length=2)),
                ('title', models.CharField(max_length=127)),
                ('description', models.TextField(max_length=32767)),
                ('short_description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='initiative',
            name='facebook',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='homepage',
            field=models.CharField(max_length=1023, null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='instagram',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='mail',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='phone',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='slug',
            field=models.SlugField(max_length=127, unique=True, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(add_slug, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='initiative',
            name='slug',
            field=models.SlugField(max_length=127, unique=True),
        ),
        migrations.RunPython(delete_loc_without_initiative, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='location',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='website.initiative'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initiativetranslation',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_translations', to='website.initiative'),
        ),
        migrations.RunPython(migrate_title_and_descriptions),
        migrations.RemoveField(
            model_name='initiativetitletext',
            name='initiative',
        ),
        migrations.DeleteModel(
            name='InitiativeDescriptionText',
        ),
        migrations.DeleteModel(
            name='InitiativeTitleText',
        ),
    ]
