# Generated by Django 4.2 on 2023-04-21 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_initiativetranslation_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='sk3_id',
        ),
        migrations.AddConstraint(
            model_name='initiativetranslation',
            constraint=models.UniqueConstraint(fields=('initiative', 'language_code'), name='max one translation per language and initiative'),
        ),
        migrations.AddField(
            model_name='initiativeimage',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_images', to='website.initiative'),
        ),
        migrations.AddConstraint(
            model_name='initiativeimage',
            constraint=models.UniqueConstraint(fields=('initiative', 'width', 'height'), name='max one image per size and initiative'),
        ),
    ]
