# Generated by Django 4.2.1 on 2023-05-04 15:06

from django.db import migrations, models

Languages = {
    'en' : {
        'english' : 'english',
        'native' : 'english',
        'flag' : '🇬🇧',
    },
    'sv' : {
        'english' : 'swedish',
        'native' : 'svenska',
        'flag' : '🇸🇪',
    },
    'de' : {
        'english' : 'german',
        'native' : 'deutsch',
        'flag' : '🇩🇪',
    },
}
Default_Lang = 'en'

def create_languages(apps, schema_editor):
    iTrans = apps.get_model("website", "InitiativeTranslation")
    langs = apps.get_model("website", "Language")
    for trans in iTrans.objects.all():
        code = trans.language_code
        try:
            langs.objects.get(code=code)
        except langs.DoesNotExist:
            language = langs.objects.create(
                code=code,
                englishName=Languages[code]['english'],
                nativeName=Languages[code]['native'],
                flag=Languages[code]['flag'],
                )
            if code == Default_Lang:
                language.default = 'd'
            language.save()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_initiativeimage_remove_initiative_sk3_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('englishName', models.CharField(max_length=20, unique=True)),
                ('nativeName', models.CharField(max_length=20, unique=True)),
                ('flag', models.CharField(max_length=2, unique=True)),
                ('code', models.SlugField(max_length=2, unique=True)),
                ('default', models.CharField(choices=[('d', 'default')], max_length=1, null=True, unique=True)),
            ],
        ),
        migrations.RunPython(create_languages, migrations.RunPython.noop),
    ]
