# Generated by Django 4.2.1 on 2023-05-04 15:24

from django.db import migrations, models
import django.db.models.deletion

def link_language(apps, schema_editor):
    iTrans = apps.get_model("website", "InitiativeTranslation")
    langs = apps.get_model("website", "Language")
    for trans in iTrans.objects.all():
        code = trans.language_code
        lang = langs.objects.get(code=code)
        trans.language = lang
        trans.save()

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativetranslation',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='language', to='website.language'),
        ),
        migrations.AddConstraint(
            model_name='initiativetranslation',
            constraint=models.UniqueConstraint(fields=('initiative', 'language'), name='max one translation per languageKey and initiative'),
        ),
        migrations.RunPython(link_language, migrations.RunPython.noop),
    ]
