# Generated by Django 4.2.1 on 2023-05-04 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_initiativetranslation_language'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='initiativetranslation',
            name='max one translation per language and initiative',
        ),
        migrations.RemoveField(
            model_name='initiativetranslation',
            name='language_code',
        ),
        migrations.AlterField(
            model_name='initiativetranslation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='language', to='website.language'),
        ),
    ]
