# Generated by Django 4.2.1 on 2023-05-10 07:04

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_initiativetranslation_language_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(default='empty text', verbose_name='Text'),
            preserve_default=False,
        ),
    ]
