# Generated by Django 4.2.1 on 2023-05-10 07:13

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_initiative_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='text',
        ),
        migrations.AlterField(
            model_name='initiativetranslation',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=32767),
        ),
    ]
