# Generated by Django 4.2.1 on 2023-05-15 12:02

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_initiative_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='facebook',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='homepage',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='instagram',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='mail',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='phone',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
