# Generated by Django 4.2.1 on 2023-05-17 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_initiative_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='promote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='initiative',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
