# Generated by Django 4.2.1 on 2023-05-17 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_regionpage_initiative_area_initiative_online_only_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='area',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
