# Generated by Django 4.2.1 on 2023-05-17 19:47

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_regionpage_alter_initiative_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=127)),
                ('order', models.IntegerField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rp_region', to='website.region')),
            ],
        ),
        migrations.AlterField(
            model_name='initiativetranslation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='it_language', to='website.language'),
        ),
        migrations.CreateModel(
            name='RegionPageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(max_length=32767)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rp_language', to='website.language')),
                ('region_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.regionpage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='regionpagetranslation',
            constraint=models.UniqueConstraint(fields=('language', 'region_page'), name='only one translation per page'),
        ),
        migrations.AddConstraint(
            model_name='regionpage',
            constraint=models.UniqueConstraint(fields=('region', 'order'), name='order for region clear'),
        ),
        migrations.AddConstraint(
            model_name='regionpage',
            constraint=models.UniqueConstraint(fields=('region', 'slug'), name='slug for region unique'),
        ),
    ]
