# Generated by Django 4.2.1 on 2023-05-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_regionpage_alter_initiativetranslation_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='area',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
