# Generated by Django 4.2.3 on 2023-07-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_initiative_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='history',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='initiative',
            name='needs_attention',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initiative',
            name='short_comment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='initiative',
            name='state',
            field=models.CharField(choices=[('h', 'hidden'), ('r', 'only via permalink'), ('p', 'published')], default='p', max_length=1),
            preserve_default=False,
        ),
    ]
