# Generated by Django 4.2.3 on 2023-07-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_initiative_history_initiative_needs_attention_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='published',
        ),
        migrations.AlterField(
            model_name='initiative',
            name='history',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
