# Generated by Django 4.2.3 on 2023-07-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_regionpagetranslation_title_alter_regionpage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionpagetranslation',
            name='sk3_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
