# Generated by Django 4.2.5 on 2023-09-19 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_regionpage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='main_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
