# Generated by Django 4.2.5 on 2023-09-19 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_initiative_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionpagetranslation',
            name='region_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rp_translations', to='website.regionpage'),
        ),
    ]
