# Generated by Django 4.2.5 on 2023-09-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_regionpagetranslation_region_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='main_image_url',
        ),
        migrations.DeleteModel(
            name='InitiativeImage',
        ),
    ]
