# Generated by Django 4.2.6 on 2024-04-07 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_remove_initiative_main_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='sk3_id',
        ),
        migrations.RemoveField(
            model_name='region',
            name='title',
        ),
        migrations.RemoveField(
            model_name='region',
            name='welcome_message_html',
        ),
        migrations.CreateModel(
            name='RegionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sk3_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=127, unique=True)),
                ('welcome_message_html', models.CharField(max_length=32767)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='r_language', to='website.language')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_translations', to='website.region')),
            ],
        ),
        migrations.AddConstraint(
            model_name='regiontranslation',
            constraint=models.UniqueConstraint(fields=('region', 'language'), name='max one translation per languageKey and region'),
        ),
    ]
