# Generated by Django 5.0.4 on 2024-04-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_remove_region_sk3_id_remove_region_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regiontranslation',
            old_name='welcome_message_html',
            new_name='welcome_message',
        ),
        migrations.AlterField(
            model_name='initiative',
            name='slug',
            field=models.SlugField(help_text='The URL part of this initiative. Cannot be changed.', max_length=127, unique=True),
        ),
    ]
