# Generated by Django 5.0.4 on 2024-04-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_rename_welcome_message_html_regiontranslation_welcome_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiontranslation',
            name='title',
            field=models.CharField(max_length=127),
        ),
    ]
