# build environment
FROM node:16.18.1-alpine as build
WORKDIR /react-frontend
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
RUN npm install
COPY . ./
ARG REACT_APP_BACKEND_URL=https://beta.smartakartan.se/api
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /react-frontend/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]